name: feature_builder
description: A sample command-line application.
version: 0.0.2
repository: https://github.com/damienissa/feature_builder

executables:
  feature_builder:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.0
  disposer: ^0.0.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
